version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: plataforma-educacional-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - plataforma-network

  nginx:
    image: nginx:alpine
    container_name: plataforma-educacional-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - plataforma-network

  db:
    image: mysql:8.0
    container_name: plataforma-educacional-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: plataforma_educacional
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: plataforma
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - plataforma-network

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: plataforma-educacional-queue
    restart: unless-stopped
    command: php artisan queue:work --sleep=3 --tries=3
    volumes:
      - ./:/var/www
    networks:
      - plataforma-network
    depends_on:
      - app
      - db

networks:
  plataforma-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
